const COMMANDS = {
  DELETE_SESSION: 'DELETE SESSION',
  GET_TIMEOUTS: 'GET TIMEOUTS',
  SET_TIMEOUTS: 'SET TIMEOUTS',
  NAVIGATE_TO: 'NAVIGATE TO',
  GET_URL: 'GET CURRENT URL',
  GET_TITLE: 'GET TITLE',
  FIND_ELEMENT: 'FIND ELEMENT',
  FIND_ELEMENTS: 'FIND ELEMENTS',
  FIND_ELEMENT_FROM_ELEMENT: ' FIND ELEMENT FROM ELEMENT',
  FIND_ELEMENTS_FROM_ELEMENT: 'FIND ELEMENTS FROM ELEMENTS',
  GET_ELEMENT_TEXT: 'GET ELEMENT TEXT',
};

module.exports = { COMMANDS };
